name: PR check pipeline

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]  

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3   

      
      - name: Built and test the service
        run: |
          echo "test"